# Site settings
title: URLucky
email:
description: URL-Team 的团队博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://urlucky.github.io"
enconding: utf-8

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
